### ISSUE TITLE
Edit as Admin broken/useless with Text Editor

### ISSUE THREAD

**Issue by thiago-g** [MacTavishAO/nautilus-admin-gtk4#5]
Hi, I saw some changes in the repo and decided to test them out, forgive me if I am being inpatient and there are still patches/updates to make it all work better.

But I noticed something, if you are using Gnome Text Editor, the edit as admin option is broken, the screen flashes for a second as if attempting to open the app but closes immediately after, I tested on files where I had permission to write and on files where I didn't have those permissions and the result is the same.

Furthermore, on Text Editor you can simply open up the file and when you save it, if you don't have the necessary permissions a pop-up window will appear asking for a password to grant administrator privileges then you can write those changes normally which makes the edit as admin option at least while using Gnome's Text Editor kinda pointless. 

I was wondering if other users might have encountered the same problem.

**Comment by MacTavishAO** [comment]
I'm using KDE now so I tested yesterday's patch after I installed nautilus from repos and Kate worked just fine.

Can you confirm Gnome Text Editor supports admin URI? Try running something like `gnome-text-editor admin:///home/user/example` from your terminal.

**Comment by MacTavishAO** [comment]
I installed nautilus, python-nautilus and gnome-text-editor on my Desktop system running Plasma 6 and everything is functioning as expected but I had to make sure `application/octet-stream` was set to `org.gnome.TextEditor.desktop` under `[Default Applications]` in `~/.config/mimeapps.list` because `Gio.content_type_guess()` returns `application/octet-stream` for text files.

While debugging this problem, I've found another bug. `Gio.content_type_guess` with empty parameter, as a result extention attempts to open non-text files (images and whatnot) with text editor. This one is fairly easy to fix.

I'm not sure about how to handle `application/octet-stream`. We could an else statement after `if text_editor is not None:` and fall back to using default application for `text/plain`. I'm open to suggestions.

**Comment by thiago-g** [comment]
I can confirm that your solution works @MacTavishAO.

However, if I may have a suggestion, I don't know how feasible or if you would even want to implement it this way, but I was thinking what if when detected that Gnome Text Editor is the default text editor the context menu 'edit as admin' simply would not present itself?

It may be a valuable addition to other editors but not necessarily to this one, as I have said before and this has been confirmed by @curable-online if you use Text Editor you can simply open the file, make changes and upon saving said file there is a privilege escalation prompt already built in the application, I find this way simpler overall and it has the benefit of not adding another option to the context menu so it appears less cluttered, leaving just the 'open as admin' option since that is quite a nice functionality to have.

**Comment by MacTavishAO** [comment]
> what if when detected that Gnome Text Editor is the default text editor the context menu 'edit as admin' simply would not present itself?

Edit as admin works with other file types too, e.g; any other non-text file with different default application than text editor. Also extension is pretty much set and forget. If you wish to do so you can remove [line 51](https://github.com/MacTavishAO/nautilus-admin-gtk4/blob/master/extension/nautilus-admin.py#L51) and be done with it.
